### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by paresh-navadiya** [raihan/ZRScrollableTabBar#1]
[tabBar scrollToTabBarWithTag:tag animated:YES];

**Comment by Vanmm** [comment]
Not working +1

**Comment by hemang-azilen** [comment]
@Vanmm 

@paresh-navadiya 

Have you guys able to find a solution on this with this library?
https://github.com/raihan/ZRScrollableTabBar/issues/2
https://github.com/raihan/ZRScrollableTabBar/issues/3

**Comment by raihan** [comment]
Fixed on latest version
