### ISSUE TITLE
How to open particular view controller when taps on a tab?

### ISSUE THREAD

**Issue by hemang-azilen** [raihan/ZRScrollableTabBar#3]
How to open particular view controller when taps on a tab?

No example given for this.

**Comment by raihan** [comment]
You can add a particular view controller when taps on view by implementing`- (void)scrollableTabBar:(ZRScrollableTabBar *)tabBar didSelectItemWithTag:(int)tag
`
delegate method. You just need to add subview of that view controller when user taps on that tab bar item.
